
### 부서 생성1
POST http://localhost:80/department/insertdpm
Content-Type: application/json

{
  "dptmName": "인사"
}
### 부서 생성2
POST http://localhost:80/department/insertdpm
Content-Type: application/json

{
  "dptmName": "개발"
}

### 사원 가입
POST http://localhost:80/employee/register
Content-Type: application/json

{
  "data": {
    "empName": "John Doe1",
    "empPhone": "123-455-7890",
    "empPwd": "password223",
    "empSex": "male",
    "empAcn": "123456789",
    "empSta": true,
    "empRk": 3,
    "dtpmNo": 1
  }
}

### 사원 리스트조회

GET http://localhost:80/employee/list
Content-Type: application/json


### 사원 퇴사

PUT http://localhost:80/employee/leave
Content-Type: application/json

{
    "empNo" : "231122",
    "rtempCont" : "북한군 침공"
}


### 휴직 사원 리스트조회
GET http://localhost:80/employee/restlist
Content-Type: application/json


### 사원 연차 조회
GET http://localhost:80/employee/restcount?empNo=231110